{
	"version": 1508669875,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/sprite-sheet0.png",
		"images/adas-sheet0.png",
		"images/ainsley-sheet0.png",
		"images/tiledbackground.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/klucz1-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/przeszkoda-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/paniego-sheet0.png",
		"images/pistolet-sheet0.png",
		"images/naboj-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/boss-sheet0.png",
		"images/nabojain-sheet0.png",
		"images/nabojain-sheet1.png",
		"images/sprite7-sheet0.png",
		"images/sprite16-sheet0.png",
		"media/0db.m4a",
		"media/0db.ogg",
		"media/sony vegas efekt rozbitej szyby.m4a",
		"media/sony vegas efekt rozbitej szyby.ogg",
		"media/+36db.m4a",
		"media/+36db.ogg",
		"media/creepy_music_box.m4a",
		"media/creepy_music_box.ogg",
		"media/scream.m4a",
		"media/scream.ogg",
		"media/final fantasy 7 battle theme (mlg airhorn remix edition).m4a",
		"media/final fantasy 7 battle theme (mlg airhorn remix edition).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}